org: karendev
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
